import './styles/globals.scss';
import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.css';
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";


export const metadata = {
  title: 'Natto-Portfolio',
  description: 'Generated by Hadiul Islam',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
